### PR TITLE
Update boot-process-overview.md

### PR DESCRIPTION
**Pull request by dcasota**
- gnu grub2 edit menu, gnu grub version, Ph5 kernel

### CODE REVIEW

**Review by mikeroySoft — CHANGES_REQUESTED** [review]
The image path should be relative to the current folder, and the image does exist in the repo.
Rather than use the githubusercontent.com url, use this local relative path instead:

../../../images/grub-edit-menu-orig.png

**Comment by mikeroySoft** [comment]
You could just rename the .png file in your fork and add to this branch, that will rename it for everyone once it's merged (and obviously this is exclusive to /docs-v5/ so it shouldn't mess the older versioned content

**Comment by dcasota** [comment]
@mikeroySoft .png file added

**Comment by dcasota** [comment]
see #1462

**Pull request closed without merging**
