### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by michaelpq**
dash is not bash.

### CODE REVIEW

**Comment by dobbymoodge** [comment]
This isn't a typo, just terrible advice.

**Comment by michaelpq** [comment]
Hehe, not wrong ;)

**Comment by snambakam** [comment]
Using dash resulted in build issues.

Sorry. We cannot accept this change at this time.

**Comment by michaelpq** [comment]
Well, you can do as it pleases you, but moving around the docs is not going to solve anything, and this advice is a *very* bad idea:
rm /bin/sh
ln -s /bin/bash /bin/sh

**Pull request closed without merging**
