### PR TITLE
dhcp.spec typo

### PR DESCRIPTION
**Pull request by dcasota**

### CODE REVIEW

**Comment by tapakund** [comment]
Hi @dcasota , we had some issues merging dev changes to 5.0. Right now the changes are done and 5.0 is in sync with dev.

Reopening the PR for 5.0.

**Comment by dcasota** [comment]
@tapakund Please do not hesitate to reject/close PR, if [incomplete, won’t implement, already fixed,..]. The dhcp.spec for instance has different release+version, hence I wasn’t sure about dependencies. Additionally, every bit change should be documented by version bump, but here, too, don’t know what else has to be added.
A pwsh script I’ve wrote does some Source0 naming integrity checks (and it checks package source updates available). There are some obvious misspellings like in this dhcp.spec. As I’ve seen from the commits, in the past weeks the existing spec integrity check has been improved.

Updates available without knowing the code changes is for nothing, but for me it fitted as indicator.

There are 5.0, 5.0 beta, origin/dev and some strange tmp branches visible indeed (?)

Facing the changes list, rewriting docs 5.0 + hugo+gh-pages, is a big amount for writers.

**Comment by dcasota** [comment]
@tapakund the packages directory https://packages.vmware.com/photon/photon_sources/5.0 hasn't been updated for a while, however in https://packages.vmware.com/photon/photon_sources/1.0/ there are strange latest updates lvm2, python3, etc. (!)

**Comment by dcasota** [comment]
@ssahani Can you help? 

1)  The typo fixes to get a valid url is for future Source0 processing tasks. dhcp.spec has been chosen as first item for this. PRs 1396-1400 were created with respect to different dhcp.spec releases: 
    - master, 5.0, 5.0-beta: 4.4.3-1
    - 4.0: 4.4.2-6
    - 4.0-openssl3: 4.4.2-4
    - 3.0: 4.3.5-10
    - 3.0-openssl3: 4.3.5-8  
     
     Please do not hesitate to reject/close PR, if [incomplete, won’t implement, already fixed,..]. 

2) In addition, see @tapakund comment https://github.com/vmware/photon/pull/1400#issuecomment-1479909328.
The pull request has been identified with conflicts that must be resolved. 

3) strange repo activites, see https://github.com/vmware/photon/pull/1400#issuecomment-1485346663: E.g. cloud-network-setup is available in the emeritus 1.0 repo (!)
    - 0.2.2: https://packages.vmware.com/photon/photon_sources/1.0/cloud-network-setup-0.2.2.tar.gz
    - 0.3: https://packages.vmware.com/photon/photon_sources/1.0/cloud-network-setup-0.3.tar.gz, however accordingly to https://github.com/vmware/cloud-network-setup/releases release 0.2.2 is latest greatest ?!

**Comment by dcasota** [comment]
not best practice. Changelog + bump version.

**Comment by dcasota** [comment]
not best practice. Changelog + bump version.  Discard old changes.

**Pull request closed without merging**
