### PR TITLE
Update working-with-kickstart.md

### PR DESCRIPTION
**Pull request by dcasota**
#1085

### CODE REVIEW

**Review by mikeroySoft — APPROVED** [review]

**Comment by ssahani** [comment]
Please rebase against 3.0 branch. Everything looks good otherwise

**Comment by dcasota** [comment]
Hi,

I apologize of reaching out, but am I eligible to process a rebase? Logged in in Github Webportal UI I haven't found a rebase / write access option. Using git rebase is completely new for me and I don't want to learn wrong steps.

```git status``` should show 1 commit I guess and to fulfill a rebase simply is ```git rebase photon/3.0``` right?
As prerequisite I've cloned the repo with the non-merged commit in vmware:photon-hugo branch and did for that
```
git clone https://github.com/dcasota/photon.git
cd photon
git remote add photon https://github.com/vmware/photon.git
git fetch photon
git checkout -b my-branch
git merge-base my-branch photon/3.0
```
After that, from the merge-base command output I've used the hash code in ```git rebase -i <hash code>```
and in Visual Code editor I've replaced "pick" with "squash" except in the first line which in my case is "Fixed broken links", then I saved&closed the Visual Studio Code editor. The second time, a list of commit msg appeared, and I saved it without any changes&closed the editor again.

The output shows a bunch of files changes but NOT the working-with-kickstart.md.
[git-output.txt](https://github.com/vmware/photon/files/6142329/git-output.txt)

What's wrong or missing? Many thanks for clarification. Daniel

**Comment by ssahani** [comment]
Please do the same edit in the doc in the 3.0 branch and generate a commit. Then force push it ```git push -u origin -f 3.0```
I tried to clone your fork, cherry pick and apply to 3.0
```
> cd photon-3-doc
> git checkout 3.0
Switched to branch '3.0'
Your branch is up to date with 'origin/3.0'.
> git am ../tmp/0001-Update-working-with-kickstart.md.patch
Applying: Update working-with-kickstart.md
error: content/en/docs-v3/user-guide/working-with-kickstart.md: does not exist in index
Patch failed at 0001 Update working-with-kickstart.md
hint: Use 'git am --show-current-patch=diff' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
~/gerrit/photon-3-doc on 3.0 *2 am 1/1 ?1 >
```

**Comment by dcasota** [comment]
In my sample above I've seen mistakes of my own. A replace of "pick" with "squash" results in a wrong replacement in a commit line beginning with "tdnf: cherry-pick some critical fixes from vmware/tdnf:dev"! In addition, a force push without knowing exactly what happens isn't good.
First I have to figure out how to see the commit f939ca4 as git status console output if pull request started in github webportal ui.

**Comment by ssahani** [comment]
Hmm figure the doc is not sync with gerrit. Let us fix it first.

**Comment by mikeroySoft** [comment]
Yah I'm confused why we'd rebase against the 3.0 branch... All the docs are in the photon-docs branch which was created with --orphan, so that it didn't have to draw a comparison between the OS and the Docs in a change (i.e. the first commit would have had like 10,000 file changes or something...)

All doc changes should just be done against photon-docs. Once any changes are made there and it's published to GitHub, the GitHub Action kicks in and builds code which ends up in the gh-pages branch.

I do need to write this up so that we're all on the same page here, but I'm not sure the right place to put that. (i.e. CONTRIBUTING.md maybe? or maybe we need a new file 'CONTRIBUTING-DOCS.md' or something...

**Comment by mikeroySoft** [comment]
That said, I'd be happy to manage/mainatin the docs delivery and PRs, etc, but I don't currently have the ability to publish... There is a change sitting in Gerrit for a week now that I've already reviewed. It'd be great if I could just review and publish.

**Comment by mikeroySoft** [comment]
and @ssahani Can we sync offline about this? I want to look into whatever makes you say that Gerrit is not in sync... We did a push last week and it was all fine. (took some doing to get a new branch, but we got there...)

**Comment by ssahani** [comment]
> and @ssahani Can we sync offline about this? I want to look into whatever makes you say that Gerrit is not in sync... We did a push last week and it was all fine. (took some doing to get a new branch, but we got there...)

sure I reworked on the original patch.  Let me ping you

**Pull request merged**
