### PR TITLE
Missing packages, README, and WORKSDIR

### PR DESCRIPTION
**Pull request by moander**

### CODE REVIEW

**Comment by toliaqat** [comment]
@moander, Thanks for the PR. Please follow the instructions at 'Contributing' section of https://vmware.github.io/photon/ to send signed CLA before I can merge the PR.

**Comment by toliaqat** [comment]
were you able to build photon inside this container? I am getting errors while building inside this container.

**Comment by moander** [comment]
Now the build fails during rpm download. 400 Bad request. Do you have any ideas?

**Comment by toliaqat** [comment]
Try again, it might be network issue. PRM download is working for me.

**Comment by toliaqat** [comment]
You would have to sync your repo and send the PR again. Preferably to dev branch.

**Comment by moander** [comment]
Replaced by #181

**Pull request closed without merging**
