### PR TITLE
Updated gce.md with several fixes and changes

### PR DESCRIPTION
**Pull request by jonasrosland**
Changed from indented code styles
Moved comments out of the scripts, together with information such as links that shouldn't be in there.
Also changed the section 9 to hopefully properly work with the named examples.

### CODE REVIEW

**Comment by toliaqat** [comment]
Hi Jonas,

We just finally able to upload a Contributor License Agreement for you to sign and send us the copy so that we can merge your PRs. Thanks a lot for all the PRs you sent so far and waiting patiently to respond to them.

See Contributing section at https://vmware.github.io/photon/ for pdf and email address to send the signed copy.

Thanks,
Touseef

**Comment by jonasrosland** [comment]
Hi @toliaqat!

When reading the CLA I see that it's mostly copied from the Apache individual contributor license agreement, which is good. But you left out important parts of that license, namely the right we as contributors continue to have over the contribution we make.

These parts are missing:

```
Thank you for your interest in The Apache Software Foundation (the
"Foundation"). In order to clarify the intellectual property license
granted with Contributions from any person or entity, the Foundation
must have a Contributor License Agreement ("CLA") on file that has
been signed by each Contributor, indicating agreement to the license
terms below. This license is for your protection as a Contributor as
well as the protection of the Foundation and its users; it does not
change your rights to use your own Contributions for any other purpose.
```

```
You accept and agree to the following terms and conditions for Your
present and future Contributions submitted to the Foundation. In
return, the Foundation shall not use Your Contributions in a way that
is contrary to the public benefit or inconsistent with its nonprofit
status and bylaws in effect at the time of the Contribution. Except
for the license granted herein to the Foundation and recipients of
software distributed by the Foundation, You reserve all right, title,
and interest in and to Your Contributions.
```

When removing this, what rights do we as contributors have left in the CLA?

**Comment by toliaqat** [comment]
Hi Jonas,

Thanks for pointing that out. Forwarded your message to our legal team and waiting for their response.

Thanks,
Touseef

**Comment by sborman** [comment]
Hi @jonasrosland 

I work in the CTO's office at VMware on our Open Source efforts (Photon is but one).  Regarding your earlier comment, you're correct in that the VMware Contributor License Agreement (CLA) closely follows that of the Apache CLA but since the VMware OSS projects are not Apache Foundation projects, our CLA does not include all the terms in the Apache CLA.

Regarding your question as to "what rights do [you] as contributors have left in the CLA":  Rights have to be affirmatively granted.  The CLA makes explicit the rights that you are granting to us.  If a right is NOT granted, then *you* retain that right.

I hope that helps.

Sean

**Comment by jonasrosland** [comment]
Hi @sborman, that clears things up. Perhaps your last statement could be stated somewhere in the CLA to further reduce confusion?

**Comment by jonasrosland** [comment]
I've signed the CLA, so if you still approve of this change you can go ahead and merge it.

**Pull request merged**
