### PR TITLE
Update Packer Examples

### PR DESCRIPTION
**Pull request by tenthirtyam**
In order to have a good experience with our community, we recommend that you read the [contributing guidelines](https://github.com/vmware-samples/packer-examples-for-vsphere/blob/main/CONTRIBUTING.md) for making a pull request.

**Summary of Pull Request**

Documentation (`vmware:photon-hugo`) - Updates to Packer Examples:
- Replaces `kickstart-through-http` with `packer-examples`
- Adds content for the related Packer projects
   - vSphere Machine Images - `vmware-samples/packer-examples-for-vsphere`
   - Vagrant Boxes - `vmware/photon-packer-templates`
- Cleans up the JSON formatting in `/docs/.../working-with-kickstart.md`

**Type of Pull Request**

- [ ] This is a bug fix.
- [ ] This is an enhancement or feature.
- [ ] This is a code style / formatting update.
- [X] This is a documentation update.
- [ ] This is a refactoring update.
- [ ] This is something else.
      Please describe: 

**Context of the Pull Request***

Updates to Packer Examples

**Related to Existing Issues**

Closes: #1259 

**Test and Documentation Coverage**

- [ ] Tests have been completed (for bug fixes / features).
- [X] Documentation has been added / updated (for bug fixes / features).

**Breaking Changes?**

- [ ] Yes, there are breaking changes.
- [X] No, there are no breaking changes.

### CODE REVIEW

**Comment by tenthirtyam** [comment]
@mikeroySoft - could you review?

Ryan

**Comment by tenthirtyam** [comment]
Any update? @ssahani

**Comment by mikeroySoft** [comment]
Thanks Ryan, was on PTO all last month so I apologies for not merging sooner!

**Comment by tenthirtyam** [comment]
Thanks, @mikeroySoft!!!

**Pull request merged**
