### PR TITLE
Update running-a-photon-os-machine-on-gce.md

### PR DESCRIPTION
**Pull request by dcasota**
#1115

### CODE REVIEW

**Review by mikeroySoft — COMMENTED** [review]
I'm not sure about this URL:
`https://packages.vmware.com/photon/<release>/<revision>/gce`

@ssahani, does this make sense? Should we replace it with 'real' values, or add a 'real' URL as an example, or is it fine as-is?

**Comment by ssahani** [comment]
> https://packages.vmware.com/photon

hmm https://packages.vmware.com/photon/4.0/ we don't have revision

**Comment by mikeroySoft** [comment]
I think that should help given the 3.0 context. We'll want to update the 4.0 docs similarly.

**Pull request merged**
