### PR TITLE
unable to calculate storage space on build iso fix

### PR DESCRIPTION
**Pull request by charliedrage**
Thanks to @dthaluru helping me on a VPS dev box as well as implementing this fix from our discussion on https://github.com/vmware/photon/issues/110

This commit fixes the calculating storage space issue when building an iso on Ubuntu/Debian.

### CODE REVIEW

**Comment by dthaluru** [comment]
Thanks for sending PR. Please check 'Contributing' section in following webpage to get started with CLA and then we will be able to merge your PR.

https://vmware.github.io/photon

**Comment by charliedrage** [comment]
Sent! Thanks.

**Comment by dthaluru** [comment]
Hi Charlie,

Can you please send CLA again to OSSContributions@vmware.com.  Looks like we did not receive any CLA yet.

Thanks,
Divya

**Comment by charliedrage** [comment]
@dthaluru 

Hi Divya, I've emailed it + cc'd you.

**Comment by toliaqat** [comment]
Thanks for sending the PR. calculatePossibleNumWorkerThreads is no longer needed in dev branch and removed. Closing this PR.

**Comment by charliedrage** [comment]
@toliaqat ummm, okay.

still doesn't fix the 
```python
cmd = "df "+constants.buildRootPath
	+ process = subprocess.Popen("%s" %cmd,shell=True,stdout=subprocess.PIPE)
```
issue. I'd appreciate having that pulled at least in order for non-vagrant users to be able to build the .iso

**Pull request closed without merging**
